name: Build Executables

on:
  push:
    paths:
      - 'client.py'
      - 'server.py'
      - '.github/workflows/build.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Wine for Windows build
        run: sudo apt-get update && sudo apt-get install -y wine
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build client executable
        run: wine pyinstaller --onefile --console client.py

      - name: Build server executable
        run: wine pyinstaller --onefile --console server.py

      - name: Upload executables
        uses: actions/upload-artifact@v4
        with:
          name: executables
          path: dist/
        
      - name: Push changes
        run: |
          git config --global user.name 'PyInstaller'
          git config --global user.email me@awdev.co
          git add .
          git commit -m "[BOT] built scripts"
          git push
