name: Build Executables

on:
  push:
    paths:
      - 'client.py'
      - 'server.py'
      - '.github/workflows/build.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          # Add other requirements if needed
          # pip install -r requirements.txt

      - name: Build client executable
        uses: JackMcKew/pyinstaller-action@v1.0.0
        with:
          script: client.py
          options: --onefile --console

      - name: Build server executable
        uses: JackMcKew/pyinstaller-action@v1.0.0
        with:
          script: server.py
          options: --onefile --console

      - name: Upload executables
        uses: actions/upload-artifact@v4
        with:
          name: executables
          path: dist/
